### ISSUE TITLE
Is there a translation project?

### ISSUE THREAD

**Issue by skyies618** [godaddy-wordpress/wc-plugin-framework#501]
I'm Japanese user of "WooCommerce Square" using this framework.
Though WooCommerce Square is fully translated in Japanese, it's difficult to use this plugin in Japanese because this framework is not translated.
I tried to translate by myself, but there are too much texts.
If there are a translation project, I will try to translate some texts.

**Comment by unfulvio-godaddy** [comment]
@skyies618 thanks for getting in touch and sorry for the terrible delay in replying to you

Unfortunately since this is just a framework, it can't be hosted on WordPress.org as a plugin or a theme to leverage community translations via Glotpress. 

However, contributors are very welcome to submit their own translations over GitHub and we will include translation files in the Framework releases.

Thank you

**Comment by unfulvio-godaddy** [comment]
I'm happy to announce that the framework has been localized in several language earlier this month. There are plenty of supported languages and we may add more in the future. For languages that are currently unsupported we'd be happy o receive third party contributions to be included in the codebase.

Please feel free to reopen this issue or ask any questions in a new issue. 

Thank you!
